#!/bin/bash
echo ${@:3:$#}
if [ "$#" -ne 1 ]; then
    echo "[ERROR]: Invalid number of parameters"
    echo "Usage: ./dev-init <github username>"
    exit 1
fi
#Checking for essential tools
git --version && \
docker -v && \
docker-compose -v && \

#cloning all apps from dev fork
app_list=( django-app )
for app in ${app_list[@]}; do
    if [ ! -d "$app" ]; then
        git clone git@github.com:$1/$app.git
        if [ "$?" -ne 1 ]; then
            echo "clone not successfull for $1/$app"
        fi
    fi
done
for app in ${app_list[@]}; do
    if [ ! -d "$app" ]; then
        echo "$app not cloned, please fork all required apps"
        exit
    fi
done
echo "Dev environment initialization complete!"
echo "Use  docker-compose up -d  to stand up the stack."
echo "Refer README.md for frequently used commands"

